// Comprehensive list of 1600+ programming languages
export const ALL_PROGRAMMING_LANGUAGES = [
  // Popular/Common Languages (prioritized at top)
  'Auto-Detect', 'Python', 'JavaScript', 'TypeScript', 'Java', 'C', 'C++', 'C#',
  'HTML', 'CSS', 'SQL', 'PHP', 'Ruby', 'Swift', 'Kotlin', 'Go', 'Rust', 'R',
  'MATLAB', 'Perl', 'Scala', 'Dart', 'Lua', 'Shell', 'PowerShell', 'Bash',

  // SQL Variants
  'SQL-DDL', 'SQL-DML', 'SQL-DCL', 'SQL-TCL', 'SQL-Triggers', 'SQL-Joins',
  'PL/SQL', 'T-SQL', 'MySQL', 'PostgreSQL', 'MongoDB Query Language', 'SQLite',

  // Special Analysis Modes
  'DSA & Algorithms', 'Flowchart Analysis', 'Handwritten Notes', 'General Document',
  'DBMS', 'Universal File/Document', 'Text Document', 'General Analysis',

  // A
  'A Manufacturing Language', 'A+', 'A++', 'ABAP', 'ABC', 'ABC ALGOL', 'ABLE',
  'ABSET', 'Abstract State Machine Language', 'ABSYS', 'Accent', 'Accent R',
  'ACL2', 'Acorn System BASIC', 'Action!', 'ActionScript', 'Active Oberon',
  'Active Server Pages', 'ActiveBasic', 'ActiveVFP', 'Actor', 'ACUCOBOL', 'Ada',
  'Ada 2005', 'Ada 2012', 'Ada 80', 'Ada 83', 'Ada 95', 'adenine', 'ADMB',
  'Advanced Business Application Language', 'Advice taker', 'AdvPL', 'Agda',
  'AgentCubes', 'AgentSheets', 'AgentSpeak', 'Agora', 'Aheui', 'AIMACO', 'AIMMS',
  'AJAX', 'AL', 'ALCOR', 'Aldor', 'Alef', 'Aleph', 'Algek', 'ALGO', 'Algoid',
  'ALGOL', 'ALGOL 58', 'ALGOL W', 'Alice', 'Allegro Common Lisp', 'Alma-0',
  'Alore', 'Alpaca', 'Alpha', 'Alphard', 'Altair BASIC', 'ALTRAN', 'Alusus',
  'Amber', 'AmbientTalk', 'AMBIT', 'Amiga Basic', 'Amiga E', 'AMOS', 'AMPL',
  'AMPLE', 'Ana', 'Analitik', 'Analytica', 'ANSYS Parametric Design Language',
  'Apache Ant', 'Apache Groovy', 'Apex', 'APL', 'APLX', 'APMonitor', 'Apple Dylan',
  'AppleScript', 'Applesoft BASIC', 'Arc', 'Arduino', 'Arendelle', 'ARexx',
  'Argh!', 'Argos', 'Argus', 'ARITH-MATIC', 'ArkTS', 'ARLA', 'ARM NEON', 'Armada',
  'ArmScript', 'ArrowFuck', 'ART', 'ASCEND', 'ASIC', 'asm.js', 'AspectC++',
  'AspectJ', 'Assembler', 'Assembly Language', 'ASSK', 'Astek', 'Asymptote',
  'Atari BASIC', 'Atari LOGO', 'Atari Microsoft BASIC', 'Atari Pascal',
  'Atari ST BASIC', 'Ateji PX', 'Atlas Autocode', 'ATOLL', 'Atom', 'ATS',
  'AtScript', 'Austral', 'Autocode', 'AutoHotkey', 'AutoIt', 'AutoLISP',
  'Automatically Programmed Tool', 'Avenue', 'Averest', 'AWK', 'Axum', 'A♯',

  // B
  'B', 'B-Prolog', 'B4X', 'Babbage', 'Baby modula-3', 'BAL', 'Ballerina',
  'Baltazar', 'BANCStar', 'BASIC', 'BASIC 8', 'BASIC A+', 'Basic For Qt',
  'BASIC Programming', 'Basic Sound Extension', 'BASIC-PLUS', 'BASIC09',
  'Basic4android', 'Basic4ppc', 'BasicX', 'Batch File', 'BBC BASIC', 'BBj',
  'BBN LISP', 'bc', 'BCPL', 'BCY', 'BeanShell', 'Beatnik', 'Beef', 'BEFLIX',
  'Befunge', 'Behavioral Description Language', 'Bertrand', 'BETA', 'Bidule',
  'Bistro', 'BitC', 'Bla', 'BLISS', 'Blitz BASIC', 'Blitz3D', 'BlitzMax',
  'BlitzPlus', 'Blockly', 'Bloom', 'BlooP and FlooP', 'Blub', 'Blue',
  'Bluespec', 'BNR Prolog', 'Bogus', 'Bon', 'Boo', 'Boomerang', 'Bosque',
  'Bourne shell', 'BPEL script', 'BQN', 'Brainfuck', 'Brief Code', 'Brutus2D',
  'bs', 'Bubble', 'Business Application Language', 'Business Intelligence Markup Language',
  'Business Process Execution Language',

  // C
  'C Intermediate Language', 'C shell', 'C*', 'C++/CLI', 'C++/CX', 'C--',
  'C/AL', 'C2', 'C3', 'CA-Telon', 'Caché ObjectScript', 'Cadence SKILL',
  'CafeOBJ', 'CAL', 'CAL Actor Language', 'CALM', 'Caml', 'Caml Light',
  'Caméléon', 'Candle', 'Cangjie', 'CaPSL', 'Carbon', 'Casio BASIC', 'Cat',
  'Categorical Programming Language', 'Catrobat', 'Cayenne', 'CBASIC', 'CDuce',
  'Cecil', 'CEEMAC', 'Cel', 'CEMMA', 'Cerner CCL', 'Ceylon', 'CFScript', 'Cg',
  'CGOL', 'Ch', 'CHAIN', 'Chaos', 'Chapel', 'Charity', 'Charm', 'Charm++',
  'ChatScript', 'Chef', 'Chez Scheme', 'CHICKEN', 'CHILL', 'Chinese BASIC',
  'ChinesePython', 'CHIP', 'CHIP-8', 'Chipmunk Basic', 'Chomski', 'ChucK',
  'Church', 'Ciao', 'CICS', 'Cilk', 'Cilk Plus', 'Cilk++', 'CiMPLE', 'Cirq',
  'Citrine', 'CLACL', 'Claire', 'Clarion', 'Clascal', 'Clean', 'Clipper',
  'CLIPS', 'CLISP', 'CLIST', 'Clojure', 'ClojureScript', 'Close to Metal',
  'CLP(R)', 'CLU', 'Cluster', 'CMS-2', 'CMU Common Lisp', 'Coarray Fortran',
  'COBOL', 'COBOL.NET', 'Cobra', 'COFFEE', 'CoffeeScript', 'COLA',
  'ColdFusion Markup Language', 'Colony Framework', 'Color BASIC', 'colorForth',
  'COMAL', 'Comet', 'Comfy', 'COMIT', 'Commodore BASIC', 'Common Intermediate Language',
  'Common Lisp', 'Common Lisp Music', 'Common Workflow Language', 'COMPACT II',
  'Compiler Description Language', 'Component Pascal', 'COMTRAN', 'Concurrent C',
  'Concurrent Euclid', 'Concurrent Haskell', 'Concurrent ML', 'Concurrent Pascal',
  'Concurrent Prolog', 'Constraint Handling Rules', 'Continuous Function Chart',
  'Control Language', 'Converge', 'Cool', 'Coopr', 'Coral 66', 'CORC',
  'Cornell University Programming Language', 'CorVision', 'CosmicOS', 'COW',
  'COWSEL', 'CPL', 'Cryptol', 'Crystal', 'CS-4', 'CSMP III', 'Csound',
  'CSS preprocessor', 'Cub', 'Cuis Smalltalk', 'Cuneiform', 'Curl', 'Curry',
  'CWEB', 'Cybil', 'CycL', 'Cyclone', 'Cypher Query Language', 'Céu', 'Cω',

  // D
  'D', 'DADiSP', 'Dafny', 'Dao', 'DAP FORTRAN', 'Dark', 'DarkBASIC', 'DARSIMCO',
  'Dartmouth ALGOL 30', 'Dartmouth BASIC', 'Darwin', 'DASL', 'Data Access Language',
  'Data General Business Basic', 'Data Language Interface', 'DataFlex', 'Datalog',
  'DatalogZ', 'Dataparallel C', 'DATATRIEVE', 'Deesel', 'Delphi', 'Delphi Prism',
  'Delta COBOL', 'Dependency Constraint Language', 'Dependent ML', 'Design By Numbers',
  'Deterministic Parallel Java', 'Dexterity', 'DG/L', 'Dhall', 'Dialect', 'DIBOL',
  'Dice', 'Digital Asset Modeling Language', 'DIGITAL Command Language',
  'Disk Extended Color BASIC', 'DIV Games Studio', 'DM', 'Dog', 'Dolittle', 'DOPE',
  'Draco', 'Dragon', 'DRAKON', 'DUP', 'Dylan', 'DYNAMO',

  // E
  'E', 'EarSketch', 'Ease', 'Easy Programming Language', 'EasyLanguage', 'eC',
  'ECL', 'ECLiPSe', 'Edinburgh IMP', 'Edison', 'Eff', 'EFL', 'EGL', 'Eiffel',
  'El-76', 'ELAN', 'ELI', 'Elixir', 'Elliott ALGOL', 'Elm', 'Eltron Programming Language',
  'Elvish', 'Emacs Lisp', 'Emerald', 'Emmental', 'Emoticon', 'Enchanting',
  'Enterprise Mashup Markup Language', 'Entry', 'Envelop', 'EP-BASIC', 'Epigram',
  'EPSILON', 'Erlang', 'ESC/POS', 'Escher', 'ESRI-Avenue', 'Esterel', 'Eta',
  'Etoys', 'Euclid', 'Euler', 'EuLisp', 'Euphoria', 'EusLisp Robot Programming Language',
  'EventScripts', 'EX-BASIC', 'EXAPT', 'EXEC 2', 'Executive Systems Problem Oriented Language',
  'EXEL', 'Expect', 'Extempore', 'Extended Backus–Naur Form', 'ExtendScript',
  'Extensible Application Markup Language', 'Extensible Embeddable Language', 'Ezhil',

  // F
  'F', 'F#', 'F*', 'F-Script', 'Face Modeling Language', 'FACT', 'Factor', 'Falcon',
  'FALSE', 'Fantasy GameBook Engine', 'Fantom', 'FARGO', 'fasm', 'FAUST', 'Felix',
  'Fenix Project', 'Fennel', 'Ferite', 'Ficl', 'FileMaker Script', 'Filetab', 'FJAX',
  'Fjölnir', 'FL', 'FLACC', 'FlagShip', 'Flapjax', 'Flavors', 'Flex', 'Flix', 'FLOW',
  'Flow Chart Language', 'Flow Java', 'FLOW-MATIC', 'Flowcode', 'Flowgorithm', 'FO(.)',
  'FOCAL', 'FOCAL-69', 'FOCUS', 'FOIL', 'FORMAC', 'Formula language', 'Forsythe',
  'Forte 4GL', 'Forth', 'Fortran', 'Fortress', 'FoxPro', 'FP', 'FP84', 'FpgaC',
  'FRACTRAN', 'Frame-based editor', 'Franz Lisp', 'FreeBASIC', 'FreeFem++', 'Frege',
  'Frenetic', 'FriCAS', 'Fril', 'Frink', 'Full BASIC', 'Futhark', 'FutureBASIC',
  'Fuzzy Control Language', 'FX-87', 'FXML',

  // G
  'G-code', 'G-Portugol', 'Gallina', 'Gambas', 'Gambit', 'Game Maker Language',
  'Game Oriented Assembly Lisp', 'GAP', 'Gauche', 'GAUSS', 'GDScript',
  'General Algebraic Modeling System', 'Generalized Automation Language',
  'Generative Modelling Language', 'GENERIC', 'GeneXus', 'Genie', 'Genus',
  'Geometric Description Language', 'GEORGE', 'GFA BASIC', 'Gibiane', 'Glass',
  'Gleam', 'Global Arrays', 'Globule', 'GNU Awk', 'GNU Common Lisp', 'GNU E',
  'GNU Guile', 'GNU MathProg', 'GNU Octave', 'GnuCOBOL', 'Go!', 'GOAL',
  'Gobstones', 'Gofer', 'GolfScript', 'Golo', 'Google Apps Script', 'Gosu',
  'GPM', 'GPSS', 'Grace', 'Grammatical Framework', 'Grap', 'Graphics Layout Engine',
  'GRASS', 'Grasshopper 3d', 'Green', 'Gremlin', 'GrGen', 'GScript', 'GT.M',
  'Guarded Horn Clauses', 'GW-BASIC', 'Gödel',

  // H
  'Hack', 'Haggis', 'HAL/S', 'Halide', 'Hamilton C shell', 'Haml', 'Handel-C',
  'Harbour', 'Hare', 'Hartmann pipeline', 'Haskell', 'Haskell 98 features', 'Haxe',
  'HC-BASIC', 'Helium', 'Hermes', 'Hewlett-Packard Graphics Language',
  'Hierarchical Editing Language for Macromolecules', 'Hierarchical Music Specification Language',
  'High Level Assembly', 'High Level Shader Language', 'High Performance Fortran',
  'Himawari', 'Hindawi Programming System', 'hoc', 'Hollywood', 'HolyC',
  'Honeywell ARGUS', 'Hop', 'Hope', 'Hopscotch', 'Hot Soup Processor',
  'HP BASIC for OpenVMS', 'HP Time-Shared BASIC', 'HP-GL', 'HPCC', 'HQ9++',
  'Hugo', 'Hume', 'Hy', 'Hybris', 'HyperFun', 'HyperTalk',

  // I
  'IBM Advanced BASIC', 'IBM BASIC', 'IBM Cross System Product', 'IBM Disk BASIC',
  'IBM Informix-4GL', 'IBM PL/S', 'IBM Query Management Facility', 'IBM RPG II',
  'IBM RPG III', 'IBM System/36 BASIC', 'ICI', 'Icon', 'ICon-L', 'Id', 'Idris',
  'IITRAN', 'Illumination Software Creator', 'ILNumerics.Net', 'Imba', 'IMP',
  'Impromptu', 'Improved Microdrive BASIC Operating System', 'Impulse C', 'Incr Tcl',
  'Inform', 'Information Processing Language', 'Ink', 'Installer', 'Instruction list',
  'Integer BASIC', 'Intel Concurrent Collections', 'Intel Parallel Building Blocks',
  'Interactive C', 'Interactive Data Language', 'INTERCAL', 'Interlisp',
  'Intermediate Programming Language', 'Interpress', 'InterSystems Caché', 'Io',
  'Ioke', 'Iota and Jot', 'IronLisp', 'IronScheme', 'ISETL', 'ISETLW', 'ISLISP',
  'ISWIM', 'Itk', 'Ixi lang', 'Izibasic',

  // J
  'J', 'J#', 'JADE', 'Jai', 'Jakarta Expression Language', 'Jakt', 'JAL', 'JaM',
  'Janet', 'Janus', 'Jasmin', 'JASS', 'Java Agent Development Framework',
  'JavaFX Script', 'JAWS Scripting Language', 'JEAN', 'Jeem', 'Jess', 'Jinja',
  'JModelica.org', 'Job Control Language', 'JoCaml', 'Joe-E', 'Join Java',
  'join-pattern', 'Jolie', 'JOSS', 'Joule', 'JOVIAL', 'Joy', 'Joyce', 'jq',
  'JR-BASIC', 'JRT', 'JS++', 'JScript .NET', 'JSFuck', 'Jsish', 'JSONiq', 'JSX',
  'Judoscript', 'Julia', 'Just BASIC',

  // K
  'K', 'Kabal', 'Kaleidoscope', 'Kalimat', 'Kara', 'Karel', 'Karel++', 'Katahdin',
  'Kawa', 'Kaya', 'KEMURI', 'Kent Recursive Calculator', 'Keykit', 'Keysight VEE',
  "Kid's Programming Language", 'Kinetic Rule Language', 'KiriKiri', 'KiXtart',
  'KL0', 'KL1', 'Klerer-May System', 'KM', 'KNITRO', 'Kodu Game Lab', 'Kojo',
  'KOMPILER', 'Koord', 'KornShell', 'KRL', 'Krypton', 'KS programming', 'KTurtle',
  'KUKA Robot Language', 'Kyma',

  // L
  'L2', 'Ladder logic', 'Language H', 'Laning and Zierler system', 'Laser BASIC',
  'Lasso', 'Latino', 'Lava', 'Lazy K', 'Lazy ML', 'LC-3', 'LCM', 'Lean', 'LEAP',
  'Leda', 'Leet', 'LEGO', 'Level I BASIC', 'Lexico', 'LFE', 'Liberty BASIC',
  'Limbo', 'LINC 4GL', 'Linda', 'Linden Scripting Language', 'Lingo', 'Links',
  'Linotte', 'Lioness', 'LIPS', 'LIS', 'LISA', 'Lisaac', 'Lisp', 'Lisp Machine Lisp',
  'Lisp-based Intelligent Software Agents', 'LispWorks', 'Lite-C', 'Lithe',
  'Little b', 'Little Smalltalk', 'LiveCode', 'LiveScript', 'Locomotive BASIC',
  'Logel', 'Logic Basic', 'Logica', 'Loglan', 'Loglan 82', 'Logo', 'Logtalk',
  'LOLCODE', 'LOOM', 'LOOPS', 'LotusScript', 'LPC', 'LSE', 'LTR', 'Luau', 'Lucee',
  'Lucid', 'Luna', 'Lush', 'Lustre', 'LYaPAS', 'Lynx', 'LZX',

  // M
  'M', 'M language', 'm4', 'Macintosh Common Lisp', 'Maclisp', 'MACRO-10', 'MacroML',
  'MAD', 'Magik', 'MAI Basic Four', 'make', 'Malbolge', 'Mama', 'Mana',
  'Managed Extensions for C++', 'MapBasic', 'Maple', 'MAPPER', 'MARK IV', 'Mary',
  'MATH-MATIC', 'Mathcad', 'Mathematica', 'Maude system', 'Mavka', 'Max', 'Maxscript',
  'Maya Embedded Language', 'MBASIC', 'MC#', 'MCPL', 'MDL', 'Mercury', 'Mesa',
  'Met English', 'Metafont', 'Metal Shading Language', 'Metaobject Protocol',
  'MetaPost', 'MetaQuotes Language MQL4/MQL5', 'MexScript', 'Micro Lua DS',
  'MicroMondes', 'Microsoft BASIC', 'Microsoft C', 'Microsoft Macro Assembler',
  'Microsoft Pascal', 'Microsoft Small Basic', 'Microsoft Visual Programming Language',
  'MIDAS', 'MIIS', 'Milk', 'MIMIC', 'MINC', 'Mind', 'Minimal BASIC', 'MiniZinc',
  'minus', 'Mirah', 'Miranda', 'mIRC scripting language', 'MIT/GNU Scheme',
  'MIVA Script', 'MIXAL', 'Mizar', 'ML', 'MLAB', 'MLisp', 'Mobile BASIC', 'Mocklisp',
  'Modelica', 'Modula', 'Modula-2', 'Modula-2+', 'Modula-3', 'Mojo', 'MOLOG',
  'Mondrian', 'Monkey X', 'MOO', 'MoonScript', 'MOTIS', 'Motoko', 'Mouse', 'Move',
  'Mozart Programming System', 'MPD', 'MS BASIC for Macintosh', 'MShell',
  'MST Workshop', 'MSX BASIC', 'MUDDL', 'Mudlle', 'MUF', 'Mulan', 'MultiLisp',
  'MUMPS', 'Music Macro Language', 'Music Markup Language', 'MUSIC-N', 'Mustache', 'MXML', 'Myrddin',

  // N
  'Nadeshiko', 'Napier88', 'NARS2000', 'Nasal', 'Nato.0+55+3d', 'NATURAL',
  'NCAR Command Language', 'NCL', 'NEAT', 'Nemerle', 'Neo Sign 0f Misery', 'nesC',
  'NESL', 'Nessus Attack Scripting Language', 'Net.Data', 'NetLogo', 'NetRexx',
  'Netwide Assembler', 'newLISP', 'NEWP', 'Newspeak', 'Newsqueak', 'NewtonScript',
  'Next Byte Codes', 'Nial', 'Nice', 'Nickle', 'NIL', 'Nim', 'Nix', 'Nock', 'NOMAD',
  'Noop', 'Nord Programming Language', 'Not eXactly C', 'Not Quite C', 'NPL', 'NQP',
  'NS Basic', 'NScripter', 'NScripter2', 'Nu', 'Nushell', 'NWScript', 'Nyquist',

  // O
  'o:XML', 'Oak', 'Oaklisp', 'Oberon', 'Oberon-2', 'Obix', 'OBJ', 'OBJ2', 'OBJ3',
  'Object Lisp', 'Object Oberon', 'Object Pascal', 'Object REXX', 'Object-Oriented Turing',
  'Object-PL/SQL', 'Objective-C', 'Objective-J', 'ObjectLOGO', 'ObjectPAL', 'ObjectStar',
  'Objlog', 'ObjVlisp', 'ObjVProlog', 'Obliq', 'OCaml', 'occam', 'occam-π', 'Octave',
  'Odin', 'OML', 'OmniMark', 'ONScripter', 'Ooc', 'Ook!', 'Oolong', 'Opa', 'Opal',
  'Open Programming Language', 'Open Roberta', 'Open Shading Language', 'OpenCL',
  'OpenEdge Advanced Business Language', 'OpenGL ES Shading Language',
  'OpenGL Shading Language', 'OpenLisp', 'Openmodelica', 'OpenMusic', 'OpenMx',
  'OpenQASM', 'OpenROAD', 'OPS5', 'Optimization Programming Language', 'OptimJ',
  'Orc', 'Orca', 'ORCA/Modula-2', 'Oriel', 'Orwell', 'OTX', 'Ox', 'Oxygene', 'Oz',

  // P
  'P', 'P#', 'P*', 'P4', 'PACT', 'Page description markup language', 'PAL', 'Pan',
  'PANORAMIC', 'Paradox', 'ParaSail', 'PARI/GP', 'Parlog', 'Parrot assembly language',
  'Parser', 'Pascal', 'Pascal Script', 'PascalABC.NET', 'Pastel', 'PATH', 'Pauscal',
  'Pawn', 'PCASTL', 'PEARL', 'Pencil Code', 'PeopleCode', 'Perl Data Language',
  'Personal Printer Data Stream', 'Petr', 'Pforth', 'Pharo', 'Phoenix Object Basic',
  'Php4delphi', 'Phrogram', 'PIC', 'Pic Micro Pascal', 'Pico', 'PicoLisp', 'Pict',
  'Piet', 'Pike', 'PILOT', 'Pipeline Pilot', 'Pixie', 'Pixilang', 'Pizza', 'Pkl',
  'PL-11', 'PL-6', 'PL/0', 'PL/8', 'PL/C', 'PL/I', 'PL/M', 'PL/P', 'PL/Perl',
  'PL/pgSQL', 'PL/Python', 'PL/Tcl', 'PL/X', 'PL360', 'PLANC', 'Plankalkül',
  'Planner', 'PLEX', 'PLEXIL', 'Pliant', 'Plus', 'Pnuts', 'Polymorphic Programming Language',
  'Polymorphic recursion', 'Polyphonic C#', 'PONIE', 'Pony', 'POP-11', 'POP-2',
  'Poplog', 'Portable Standard Lisp', 'Portal', 'Portlet', 'PostScript', 'POSXML',
  'Potion', 'PottersWheel', 'POW!', 'Power Fx', 'PowerBASIC', 'PowerHouse',
  'Powerscript', 'PPL', 'PQL', 'Praspel', 'PRINT', 'Printer Command Language',
  'Printer Job Language', 'Pro*C', 'Processing', 'Processing.js', 'Procyon', 'Prodel',
  'Production Rule Representation', 'Profile Scripting Language', 'PROGOL',
  'Program Composition Notation', 'Programming Computable Functions',
  'Programming Language for Business', 'Programming with Big Data in R', 'Prograph',
  'PROGRES', 'Project Builder', 'Project Verona', 'Prolog', 'PROMAL', 'PROSA',
  'PROSE', 'ProSet', 'Protel', 'Proteus', 'Prova', 'ProvideX', 'PS 440', 'PS-algol',
  'Ptolemy Project', 'PTQL', 'Pure', 'Pure Data', 'PureBasic', 'PureScript', 'PV-Wave',
  'PWCT', 'Pxem', 'Py', 'PyLinda', 'Pyrex', 'Pythagoras', 'PyUnit', "P''",

  // Q
  'Q', 'Q (Kx Systems)', 'Q#', 'Qalb', 'QB64', 'QBasic', 'Qi', 'QML', 'Qore', 'Qu',
  'QuakeC', 'Quantum computation language', 'Quartz Composer', 'QUEL', 'QuickBASIC',
  'QuickPascal', 'QUIKTRAN', 'QUILL',

  // R
  'R++', 'Racket', 'Raku', 'rank', 'Rant', 'RAPID', 'RapidBatch', 'Rapira', 'Raptor',
  'RascalMPL', 'Ratfor', 'Rational Modeling Language', 'RBASIC', 'rc', 'RCML',
  'Reaktor', 'Real-time Cmix', 'REALBasic', 'Realtime Programming Language', 'REBOL',
  'Redcode', 'Refal', 'Reia', 'Relevance Language', "Ren'Py", 'Rex', 'REXX', 'RGSS',
  'Ring', 'RiscLua', 'Robic', 'Robik', 'Robot Battle', 'Robotc', 'Roc', 'Rockstar',
  'Rocky Mountain BASIC', 'Rocq', 'ROOP', 'ROOT', 'Roy', 'Rpal', 'RPG', 'RPG Code',
  'RPG IV', 'RPL', 'RPython', 'RSL', 'RTL/2', 'RTML', 'Ruby (hardware description language)',
  'Run BASIC', 'RUR-PLE',

  // S
  'S', 'S-algol', 'S-PLUS', 'S/SL', 'S2', 'S3', 'SA-C', 'SabreTalk', 'SAC',
  'SAKO', 'SAM BASIC', 'SAM76', 'SAMPL', 'SARL', 'SAS Language', 'SASL', 'Sass',
  'SassScript', 'Sather', 'SATySFi', 'Sawzall', 'Scallop', 'Scheme',
  'Scientific Vector Language', 'Scilab', 'SCM', 'Scol', 'SCOOP', 'Scratch',
  'ScratchJr', 'Script', 'Script-Fu', 'Script.NET', 'Scripter3', 'Scriptlet',
  'Scriptol', 'SCUMM', 'Secure Operations Language', 'sed', 'Seed7', 'Self',
  'Sense', 'SenseTalk', 'SequenceL', 'Server Side Includes', 'SETL', 'SETL2',
  'Shakespeare', 'Shape Expressions', 'SheerPower4GL', 'shell script', 'Shen',
  'Short Code', 'SICStus Prolog', 'Sieve', 'Sigma', 'SIGNAL', 'SIMPL', 'SiMPLE',
  'Simple Yet Powerful Scripting Language', 'SIMSCRIPT', 'Simul', 'Simula',
  'Simulink', 'Sinclair BASIC', 'Sing#', 'Singularity', 'SISAL', 'SK8', 'SKILL',
  'SL5', 'SLAM', 'Slate', 'Sleep', 'SLIP', 'SMALL', 'SmallBASIC', 'Smalltalk',
  'Smart Pascal', 'SMETANA', 'SMIL Timesheets', 'SMT-LIB', 'SNAP', 'Snap!',
  'Snap4Arduino', 'Snek', 'SNOBOL', 'SNOBOL4', 'Snostorm', 'Snowball', 'Solidity',
  'SolidThinking Embed', 'Sort Merge Generator', 'Source', 'SP/k', 'SPARQL',
  'Speakeasy', 'Spec#', 'Speedcoding', 'Spice', 'Spice Lisp', 'SpiderBasic',
  'Split-C', 'Spoon', 'SQL*Plus', 'SQL/PSM', 'SQLPL', 'SQR', 'Squeak', 'SR',
  'StaDyn', 'Stagecast Creator', 'Stan', 'Standard ML', 'Standard ML of New Jersey',
  'Stanford Artificial Intelligence Language', 'Stanislaus', 'Starlark', 'StarLogo',
  'Stata', 'Stateflow', 'STELLA', 'Stencyl', 'Storyboard', 'STOS BASIC', 'Strand',
  'STRINGCOMP', 'Strongtalk', 'Structured Audio Orchestra Language', 'Structured text',
  'Stylus', 'SubL', 'Subtext', 'Sue', 'Suika2', 'Suneido', 'Superbase database',
  'SuperBASIC', 'SuperCollider', 'SuperNova', 'SuperPascal', 'Superplan', 'SuperTalk',
  'Svelte', 'SWI-Prolog', 'Swift (parallel scripting language)', 'SYCL', 'SYMPL',
  'Synchronized Multimedia Integration Language', 'Synergy DBL',
  'Syntax Definition Formalism', 'SynthEdit', 'SystemBuilder/SB+', 'SystemVerilog',

  // T
  'T', 'T++', 'Table Producing Language', 'TACL', 'TACPOL', 'TADS', 'Tcl', 'TclX',
  'Tea', 'TECO', 'TELCOMP', 'Telescript', 'Teml', 'Template Attribute Language',
  'TeX', 'Text Executive Programming Language', 'Text Processing Utility',
  'The join calculus language', 'thinBasic', 'THINK C', 'Thue', 'TI BASIC',
  'TI-BASIC 83', 'TigerJython', 'Timber', 'Tink', 'Tiny', 'Tiny BASIC', 'TinyScheme',
  'TJS2', 'TLA+', 'TMG', 'TNSDL', 'Toi', 'TOM', 'TOMVIEW', 'ToonTalk',
  'Topology and Orchestration Specification for Cloud Applications', 'Torino',
  'Torque', 'TouchDesigner', 'TouchDevelop', 'TRAC', 'Trade Space Visualizer',
  'Transact-SQL', 'Transaction Application Language', 'TREE-META', 'Treetop',
  'Trellis-Owl', 'Tritium', 'Triton', 'True BASIC', 'TTCN', 'TTCN-3', 'TTM',
  'TTSneo', 'Turbo Basic', 'Turbo C++', 'Turbo Pascal', 'Turbo-BASIC XL', 'Turbo51',
  'Turing', 'Turing+', 'Turtlestitch', 'TUTOR', 'TUZ-3', 'Twelf', 'TXL',

  // U
  'Ubercode', 'UCBLogo', 'UCSD Pascal', 'Umple', 'UNCOL', 'UNICODE', 'Unicon',
  'Uniface', 'Unified Expression Language', 'Unified Parallel C', 'Unilang', 'UNITY',
  'Universal Test Specification Language', 'Unlambda', 'Unobtrusive JavaScript',
  'UnrealScript', 'Ur/Web', 'URBI', 'urbiscript', 'URQ', 'UWSC',

  // V
  'V', 'Vala', 'Variable Assembly Language', 'VAX Macro', 'Verse',
  'Vienna Definition Language', 'Vilnius BASIC', 'Vimscript', 'Vintage BASIC',
  'Viola', 'Viper', 'VIPLE', 'VisiCalc', 'Visual Basic', 'Visual Basic (.NET)',
  'Visual Basic 6', 'Visual Basic Script', 'Visual DialogScript', 'Visual FoxPro',
  'Visual J++', 'Visual Logic', 'Visual Objects', 'Visual Prolog', 'Visual T#', 'vvvv',

  // W
  'WATFIV', 'WEB', 'Web Language', 'WebAssembly', 'WebGL', 'WebGPU Shading Language',
  'webMethods Flow', 'wenyan‑lang', 'Whiley', 'Whitespace', 'WICS', 'Wiring',
  'WLanguage', 'WMLScript', 'Wolfram Language', 'wollok', 'WordBASIC',
  'Work Flow Language', 'WQL', 'Wren', 'WSFN', 'wxBasic', 'Wyvern',

  // X
  'X#', 'X++', 'X-BASIC', 'X10', 'x86 assembly language', 'XACML', 'XBase++',
  'XBasic', 'XBLite', 'XC', 'XcalableMP', 'XCore XS1', 'XCY', 'XDL', 'xHarbour',
  'XL', 'XLNT', 'XML', 'XML User Interface Language', 'XMTC', 'XOD', 'Xojo',
  'XOTcl', 'XPath', 'XPL', 'XPL0', 'XProc', 'XProfan', 'XQuery', 'XSB', 'XSLT',
  'Xtend', 'XUpdate',

  // Y
  'YAWL', 'Yellow', 'Yoix', 'Yorick', 'YS MegaBasic',

  // Z
  'Z++', 'Zebra', 'Zenith Parsing Engine', 'Zeno', 'ZetaLisp', 'ZhPy', 'Zig', 'ZIL',
  'Zimbu', 'Zonnon', 'Zope Page Templates', 'ZOPL', 'ZPL',

  // Other/Special
  '*Lisp', '.QL', '///', '1C:Enterprise', '2.PAK', '2APL', '3APL', '3DMLW', '4DOS',
  '4th Dimension', 'Ć', 'λProlog', 'WASM', 'GraphQL', 'JSON', 'YAML', 'TOML', 'XML',
  'Markdown', 'LaTeX', 'Regex', 'Protocol Buffers', 'Thrift', 'gRPC',
  'Docker', 'Kubernetes YAML', 'Terraform', 'Ansible', 'Puppet', 'Chef',
  'Makefile', 'CMake', 'Gradle', 'Maven', 'Bazel', 'Ninja',
  'LLVM IR', 'SPIR-V', 'PTX', 'CUDA', 'OpenCL Kernel',
  'Verilog', 'VHDL', 'SystemC', 'Chisel', 'SpinalHDL', 'MyHDL',
  'Scratch 3.0', 'Blockly', 'App Inventor', 'Alice 3', 'Greenfoot',
  'React JSX', 'Vue SFC', 'Angular Template', 'Svelte Component',
  'GLSL', 'HLSL', 'Metal', 'WGSL', 'ShaderLab',
];

// Get a shorter list of popular languages for quick selection
export const POPULAR_LANGUAGES = [
  'Auto-Detect', 'Python', 'JavaScript', 'TypeScript', 'Java', 'C', 'C++', 'C#',
  'HTML', 'CSS', 'SQL', 'PHP', 'Ruby', 'Swift', 'Kotlin', 'Go', 'Rust', 'R',
  'MATLAB', 'Perl', 'Scala', 'Dart', 'Lua', 'Shell', 'PowerShell', 'Bash',
  'SQL-DDL', 'SQL-DML', 'SQL-DCL', 'SQL-TCL', 'SQL-Triggers', 'SQL-Joins',
  'PL/SQL', 'T-SQL', 'MongoDB Query Language',
  'DSA & Algorithms', 'Flowchart Analysis', 'Handwritten Notes', 'General Document',
];
