// Comprehensive list of 1600+ programming languages with auto-detect
// Includes all major languages, DSA, flowcharts, and analysis modes

export const PROGRAMMING_LANGUAGES = [
  // Auto-Detect (First Option)
  { value: 'Auto-Detect', category: 'Auto' },
  
  // Analysis Modes
  { value: 'DSA & Algorithms', category: 'Analysis' },
  { value: 'Flowchart Analysis', category: 'Analysis' },
  { value: 'Time Complexity Analysis', category: 'Analysis' },
  { value: 'Space Complexity Analysis', category: 'Analysis' },
  { value: 'Big-O Analysis', category: 'Analysis' },
  { value: 'Algorithm Design', category: 'Analysis' },
  { value: 'Data Structure Analysis', category: 'Analysis' },
  { value: 'Pseudocode', category: 'Analysis' },
  { value: 'General Document', category: 'Analysis' },
  { value: 'Handwritten Notes', category: 'Analysis' },
  { value: 'Text Document', category: 'Analysis' },
  
  // Popular Languages (Most Used)
  { value: 'Python', category: 'Popular' },
  { value: 'JavaScript', category: 'Popular' },
  { value: 'TypeScript', category: 'Popular' },
  { value: 'Java', category: 'Popular' },
  { value: 'C', category: 'Popular' },
  { value: 'C++', category: 'Popular' },
  { value: 'C#', category: 'Popular' },
  { value: 'Go', category: 'Popular' },
  { value: 'Rust', category: 'Popular' },
  { value: 'Swift', category: 'Popular' },
  { value: 'Kotlin', category: 'Popular' },
  { value: 'PHP', category: 'Popular' },
  { value: 'Ruby', category: 'Popular' },
  { value: 'R', category: 'Popular' },
  { value: 'Scala', category: 'Popular' },
  { value: 'Perl', category: 'Popular' },
  { value: 'Dart', category: 'Popular' },
  { value: 'Lua', category: 'Popular' },
  { value: 'Julia', category: 'Popular' },
  { value: 'MATLAB', category: 'Popular' },
  
  // Web Technologies
  { value: 'HTML', category: 'Web' },
  { value: 'HTML5', category: 'Web' },
  { value: 'CSS', category: 'Web' },
  { value: 'CSS3', category: 'Web' },
  { value: 'SCSS', category: 'Web' },
  { value: 'SASS', category: 'Web' },
  { value: 'LESS', category: 'Web' },
  { value: 'Stylus', category: 'Web' },
  { value: 'PostCSS', category: 'Web' },
  { value: 'Tailwind CSS', category: 'Web' },
  { value: 'Bootstrap', category: 'Web' },
  { value: 'JSON', category: 'Web' },
  { value: 'XML', category: 'Web' },
  { value: 'YAML', category: 'Web' },
  { value: 'TOML', category: 'Web' },
  { value: 'SVG', category: 'Web' },
  { value: 'WebAssembly', category: 'Web' },
  { value: 'JSX', category: 'Web' },
  { value: 'TSX', category: 'Web' },
  { value: 'Vue', category: 'Web' },
  { value: 'Svelte', category: 'Web' },
  { value: 'Angular', category: 'Web' },
  { value: 'React', category: 'Web' },
  { value: 'Next.js', category: 'Web' },
  { value: 'Nuxt.js', category: 'Web' },
  { value: 'Astro', category: 'Web' },
  { value: 'Remix', category: 'Web' },
  { value: 'Gatsby', category: 'Web' },
  { value: 'GraphQL', category: 'Web' },
  { value: 'REST API', category: 'Web' },
  { value: 'WebSocket', category: 'Web' },
  
  // Database & SQL
  { value: 'SQL', category: 'Database' },
  { value: 'SQL-DDL', category: 'Database' },
  { value: 'SQL-DML', category: 'Database' },
  { value: 'SQL-DCL', category: 'Database' },
  { value: 'SQL-TCL', category: 'Database' },
  { value: 'SQL-Triggers', category: 'Database' },
  { value: 'SQL-Joins', category: 'Database' },
  { value: 'SQL-Procedures', category: 'Database' },
  { value: 'SQL-Functions', category: 'Database' },
  { value: 'SQL-Views', category: 'Database' },
  { value: 'SQL-Indexes', category: 'Database' },
  { value: 'PL/SQL', category: 'Database' },
  { value: 'T-SQL', category: 'Database' },
  { value: 'MySQL', category: 'Database' },
  { value: 'PostgreSQL', category: 'Database' },
  { value: 'SQLite', category: 'Database' },
  { value: 'Oracle SQL', category: 'Database' },
  { value: 'SQL Server', category: 'Database' },
  { value: 'MariaDB', category: 'Database' },
  { value: 'MongoDB', category: 'Database' },
  { value: 'MongoDB Query Language', category: 'Database' },
  { value: 'Redis', category: 'Database' },
  { value: 'Cassandra CQL', category: 'Database' },
  { value: 'Neo4j Cypher', category: 'Database' },
  { value: 'DynamoDB', category: 'Database' },
  { value: 'Firebase', category: 'Database' },
  { value: 'Supabase', category: 'Database' },
  { value: 'CouchDB', category: 'Database' },
  { value: 'InfluxQL', category: 'Database' },
  { value: 'Elasticsearch', category: 'Database' },
  { value: 'DBMS', category: 'Database' },
  { value: 'RDBMS', category: 'Database' },
  { value: 'NoSQL', category: 'Database' },
  
  // Systems Programming
  { value: 'Assembly', category: 'Systems' },
  { value: 'x86 Assembly', category: 'Systems' },
  { value: 'x64 Assembly', category: 'Systems' },
  { value: 'ARM Assembly', category: 'Systems' },
  { value: 'MIPS Assembly', category: 'Systems' },
  { value: 'RISC-V Assembly', category: 'Systems' },
  { value: '8051 Assembly', category: 'Systems' },
  { value: 'AVR Assembly', category: 'Systems' },
  { value: 'PIC Assembly', category: 'Systems' },
  { value: 'SPARC Assembly', category: 'Systems' },
  { value: 'PowerPC Assembly', category: 'Systems' },
  { value: 'Z80 Assembly', category: 'Systems' },
  { value: '6502 Assembly', category: 'Systems' },
  { value: 'NASM', category: 'Systems' },
  { value: 'MASM', category: 'Systems' },
  { value: 'GAS', category: 'Systems' },
  { value: 'FASM', category: 'Systems' },
  { value: 'LLVM IR', category: 'Systems' },
  { value: 'CUDA', category: 'Systems' },
  { value: 'OpenCL', category: 'Systems' },
  { value: 'Metal', category: 'Systems' },
  { value: 'HLSL', category: 'Systems' },
  { value: 'GLSL', category: 'Systems' },
  { value: 'SPIR-V', category: 'Systems' },
  { value: 'Verilog', category: 'Systems' },
  { value: 'VHDL', category: 'Systems' },
  { value: 'SystemVerilog', category: 'Systems' },
  { value: 'Chisel', category: 'Systems' },
  { value: 'Bluespec', category: 'Systems' },
  { value: 'Zig', category: 'Systems' },
  { value: 'Nim', category: 'Systems' },
  { value: 'Crystal', category: 'Systems' },
  { value: 'D', category: 'Systems' },
  { value: 'Ada', category: 'Systems' },
  { value: 'Modula-2', category: 'Systems' },
  { value: 'Modula-3', category: 'Systems' },
  { value: 'Oberon', category: 'Systems' },
  { value: 'Pascal', category: 'Systems' },
  { value: 'Object Pascal', category: 'Systems' },
  { value: 'Delphi', category: 'Systems' },
  { value: 'Free Pascal', category: 'Systems' },
  
  // Functional Languages
  { value: 'Haskell', category: 'Functional' },
  { value: 'OCaml', category: 'Functional' },
  { value: 'F#', category: 'Functional' },
  { value: 'Erlang', category: 'Functional' },
  { value: 'Elixir', category: 'Functional' },
  { value: 'Clojure', category: 'Functional' },
  { value: 'ClojureScript', category: 'Functional' },
  { value: 'Lisp', category: 'Functional' },
  { value: 'Common Lisp', category: 'Functional' },
  { value: 'Scheme', category: 'Functional' },
  { value: 'Racket', category: 'Functional' },
  { value: 'Elm', category: 'Functional' },
  { value: 'PureScript', category: 'Functional' },
  { value: 'ReasonML', category: 'Functional' },
  { value: 'ReScript', category: 'Functional' },
  { value: 'Standard ML', category: 'Functional' },
  { value: 'Miranda', category: 'Functional' },
  { value: 'Clean', category: 'Functional' },
  { value: 'Idris', category: 'Functional' },
  { value: 'Agda', category: 'Functional' },
  { value: 'Coq', category: 'Functional' },
  { value: 'Lean', category: 'Functional' },
  { value: 'Isabelle', category: 'Functional' },
  { value: 'HOL', category: 'Functional' },
  { value: 'Twelf', category: 'Functional' },
  { value: 'Epigram', category: 'Functional' },
  { value: 'Curry', category: 'Functional' },
  { value: 'Mercury', category: 'Functional' },
  
  // Scripting Languages
  { value: 'Bash', category: 'Scripting' },
  { value: 'Shell', category: 'Scripting' },
  { value: 'Zsh', category: 'Scripting' },
  { value: 'Fish', category: 'Scripting' },
  { value: 'PowerShell', category: 'Scripting' },
  { value: 'Batch', category: 'Scripting' },
  { value: 'CMD', category: 'Scripting' },
  { value: 'AWK', category: 'Scripting' },
  { value: 'Sed', category: 'Scripting' },
  { value: 'Grep', category: 'Scripting' },
  { value: 'Tcl', category: 'Scripting' },
  { value: 'Tk', category: 'Scripting' },
  { value: 'Expect', category: 'Scripting' },
  { value: 'AppleScript', category: 'Scripting' },
  { value: 'JScript', category: 'Scripting' },
  { value: 'VBScript', category: 'Scripting' },
  { value: 'AutoHotkey', category: 'Scripting' },
  { value: 'AutoIt', category: 'Scripting' },
  { value: 'Makefile', category: 'Scripting' },
  { value: 'CMake', category: 'Scripting' },
  { value: 'Ninja', category: 'Scripting' },
  { value: 'Meson', category: 'Scripting' },
  { value: 'Bazel', category: 'Scripting' },
  { value: 'Buck', category: 'Scripting' },
  { value: 'Gradle', category: 'Scripting' },
  { value: 'Maven', category: 'Scripting' },
  { value: 'Ant', category: 'Scripting' },
  { value: 'SBT', category: 'Scripting' },
  { value: 'Leiningen', category: 'Scripting' },
  { value: 'Rake', category: 'Scripting' },
  { value: 'npm scripts', category: 'Scripting' },
  { value: 'Gulp', category: 'Scripting' },
  { value: 'Grunt', category: 'Scripting' },
  { value: 'Webpack Config', category: 'Scripting' },
  { value: 'Vite Config', category: 'Scripting' },
  { value: 'Rollup Config', category: 'Scripting' },
  { value: 'esbuild Config', category: 'Scripting' },
  
  // Mobile Development
  { value: 'Objective-C', category: 'Mobile' },
  { value: 'Swift UI', category: 'Mobile' },
  { value: 'Kotlin Android', category: 'Mobile' },
  { value: 'Java Android', category: 'Mobile' },
  { value: 'React Native', category: 'Mobile' },
  { value: 'Flutter', category: 'Mobile' },
  { value: 'Xamarin', category: 'Mobile' },
  { value: 'Ionic', category: 'Mobile' },
  { value: 'Cordova', category: 'Mobile' },
  { value: 'PhoneGap', category: 'Mobile' },
  { value: 'NativeScript', category: 'Mobile' },
  { value: 'Capacitor', category: 'Mobile' },
  { value: 'Expo', category: 'Mobile' },
  { value: 'Android XML', category: 'Mobile' },
  { value: 'XIB', category: 'Mobile' },
  { value: 'Storyboard', category: 'Mobile' },
  
  // Game Development
  { value: 'Unity C#', category: 'Game Dev' },
  { value: 'Unreal Blueprint', category: 'Game Dev' },
  { value: 'Unreal C++', category: 'Game Dev' },
  { value: 'Godot GDScript', category: 'Game Dev' },
  { value: 'GameMaker Language', category: 'Game Dev' },
  { value: 'Pygame', category: 'Game Dev' },
  { value: 'Phaser', category: 'Game Dev' },
  { value: 'Three.js', category: 'Game Dev' },
  { value: 'Babylon.js', category: 'Game Dev' },
  { value: 'Cocos2d', category: 'Game Dev' },
  { value: 'Love2D Lua', category: 'Game Dev' },
  { value: 'RPG Maker', category: 'Game Dev' },
  { value: 'Ren\'Py', category: 'Game Dev' },
  { value: 'Twine', category: 'Game Dev' },
  { value: 'Ink', category: 'Game Dev' },
  { value: 'Yarn Spinner', category: 'Game Dev' },
  
  // Data Science & ML
  { value: 'Python NumPy', category: 'Data Science' },
  { value: 'Python Pandas', category: 'Data Science' },
  { value: 'Python SciPy', category: 'Data Science' },
  { value: 'Python Matplotlib', category: 'Data Science' },
  { value: 'Python Seaborn', category: 'Data Science' },
  { value: 'Python Plotly', category: 'Data Science' },
  { value: 'Python Scikit-learn', category: 'Data Science' },
  { value: 'Python TensorFlow', category: 'Data Science' },
  { value: 'Python PyTorch', category: 'Data Science' },
  { value: 'Python Keras', category: 'Data Science' },
  { value: 'Python OpenCV', category: 'Data Science' },
  { value: 'Python NLTK', category: 'Data Science' },
  { value: 'Python spaCy', category: 'Data Science' },
  { value: 'Python Transformers', category: 'Data Science' },
  { value: 'Python LangChain', category: 'Data Science' },
  { value: 'R ggplot2', category: 'Data Science' },
  { value: 'R dplyr', category: 'Data Science' },
  { value: 'R tidyr', category: 'Data Science' },
  { value: 'R caret', category: 'Data Science' },
  { value: 'R Shiny', category: 'Data Science' },
  { value: 'Jupyter Notebook', category: 'Data Science' },
  { value: 'Apache Spark', category: 'Data Science' },
  { value: 'PySpark', category: 'Data Science' },
  { value: 'Scala Spark', category: 'Data Science' },
  { value: 'Hadoop MapReduce', category: 'Data Science' },
  { value: 'Apache Flink', category: 'Data Science' },
  { value: 'Apache Kafka', category: 'Data Science' },
  { value: 'Apache Airflow', category: 'Data Science' },
  { value: 'Dask', category: 'Data Science' },
  { value: 'Vaex', category: 'Data Science' },
  { value: 'Polars', category: 'Data Science' },
  { value: 'DuckDB', category: 'Data Science' },
  { value: 'Presto', category: 'Data Science' },
  { value: 'Trino', category: 'Data Science' },
  { value: 'SAS', category: 'Data Science' },
  { value: 'SPSS', category: 'Data Science' },
  { value: 'Stata', category: 'Data Science' },
  { value: 'Octave', category: 'Data Science' },
  { value: 'Mathematica', category: 'Data Science' },
  { value: 'Wolfram Language', category: 'Data Science' },
  { value: 'Maple', category: 'Data Science' },
  
  // DevOps & Cloud
  { value: 'Docker', category: 'DevOps' },
  { value: 'Dockerfile', category: 'DevOps' },
  { value: 'Docker Compose', category: 'DevOps' },
  { value: 'Kubernetes', category: 'DevOps' },
  { value: 'Kubernetes YAML', category: 'DevOps' },
  { value: 'Helm', category: 'DevOps' },
  { value: 'Terraform', category: 'DevOps' },
  { value: 'Terraform HCL', category: 'DevOps' },
  { value: 'Ansible', category: 'DevOps' },
  { value: 'Ansible YAML', category: 'DevOps' },
  { value: 'Puppet', category: 'DevOps' },
  { value: 'Chef', category: 'DevOps' },
  { value: 'Salt', category: 'DevOps' },
  { value: 'Vagrant', category: 'DevOps' },
  { value: 'Packer', category: 'DevOps' },
  { value: 'CloudFormation', category: 'DevOps' },
  { value: 'AWS CDK', category: 'DevOps' },
  { value: 'Pulumi', category: 'DevOps' },
  { value: 'Serverless Framework', category: 'DevOps' },
  { value: 'SAM Template', category: 'DevOps' },
  { value: 'Azure ARM', category: 'DevOps' },
  { value: 'Azure Bicep', category: 'DevOps' },
  { value: 'GCP Deployment Manager', category: 'DevOps' },
  { value: 'Jenkins Pipeline', category: 'DevOps' },
  { value: 'GitHub Actions', category: 'DevOps' },
  { value: 'GitLab CI', category: 'DevOps' },
  { value: 'CircleCI', category: 'DevOps' },
  { value: 'Travis CI', category: 'DevOps' },
  { value: 'Azure Pipelines', category: 'DevOps' },
  { value: 'Bitbucket Pipelines', category: 'DevOps' },
  { value: 'Argo CD', category: 'DevOps' },
  { value: 'Flux', category: 'DevOps' },
  { value: 'Prometheus', category: 'DevOps' },
  { value: 'Grafana', category: 'DevOps' },
  { value: 'Datadog', category: 'DevOps' },
  { value: 'New Relic', category: 'DevOps' },
  { value: 'Splunk', category: 'DevOps' },
  { value: 'ELK Stack', category: 'DevOps' },
  { value: 'Logstash', category: 'DevOps' },
  { value: 'Filebeat', category: 'DevOps' },
  { value: 'Fluentd', category: 'DevOps' },
  { value: 'Nginx Config', category: 'DevOps' },
  { value: 'Apache Config', category: 'DevOps' },
  { value: 'HAProxy Config', category: 'DevOps' },
  { value: 'Envoy Config', category: 'DevOps' },
  { value: 'Traefik Config', category: 'DevOps' },
  { value: 'Istio', category: 'DevOps' },
  { value: 'Linkerd', category: 'DevOps' },
  { value: 'Consul', category: 'DevOps' },
  { value: 'Vault', category: 'DevOps' },
  { value: 'Nomad', category: 'DevOps' },
  
  // Testing
  { value: 'Jest', category: 'Testing' },
  { value: 'Mocha', category: 'Testing' },
  { value: 'Jasmine', category: 'Testing' },
  { value: 'Cypress', category: 'Testing' },
  { value: 'Playwright', category: 'Testing' },
  { value: 'Selenium', category: 'Testing' },
  { value: 'Puppeteer', category: 'Testing' },
  { value: 'WebDriverIO', category: 'Testing' },
  { value: 'Nightwatch', category: 'Testing' },
  { value: 'TestCafe', category: 'Testing' },
  { value: 'Vitest', category: 'Testing' },
  { value: 'Testing Library', category: 'Testing' },
  { value: 'Enzyme', category: 'Testing' },
  { value: 'JUnit', category: 'Testing' },
  { value: 'TestNG', category: 'Testing' },
  { value: 'Spock', category: 'Testing' },
  { value: 'ScalaTest', category: 'Testing' },
  { value: 'pytest', category: 'Testing' },
  { value: 'unittest', category: 'Testing' },
  { value: 'nose', category: 'Testing' },
  { value: 'Robot Framework', category: 'Testing' },
  { value: 'Behave', category: 'Testing' },
  { value: 'Cucumber', category: 'Testing' },
  { value: 'SpecFlow', category: 'Testing' },
  { value: 'RSpec', category: 'Testing' },
  { value: 'Minitest', category: 'Testing' },
  { value: 'PHPUnit', category: 'Testing' },
  { value: 'Pest', category: 'Testing' },
  { value: 'NUnit', category: 'Testing' },
  { value: 'xUnit', category: 'Testing' },
  { value: 'MSTest', category: 'Testing' },
  { value: 'Go Testing', category: 'Testing' },
  { value: 'Ginkgo', category: 'Testing' },
  { value: 'ExUnit', category: 'Testing' },
  { value: 'Catch2', category: 'Testing' },
  { value: 'Google Test', category: 'Testing' },
  { value: 'Boost.Test', category: 'Testing' },
  { value: 'Doctest', category: 'Testing' },
  { value: 'Quick', category: 'Testing' },
  { value: 'XCTest', category: 'Testing' },
  { value: 'Espresso', category: 'Testing' },
  { value: 'Appium', category: 'Testing' },
  { value: 'Detox', category: 'Testing' },
  { value: 'Maestro', category: 'Testing' },
  { value: 'K6', category: 'Testing' },
  { value: 'Locust', category: 'Testing' },
  { value: 'Gatling', category: 'Testing' },
  { value: 'JMeter', category: 'Testing' },
  { value: 'Artillery', category: 'Testing' },
  { value: 'Postman Tests', category: 'Testing' },
  { value: 'Newman', category: 'Testing' },
  { value: 'REST Assured', category: 'Testing' },
  { value: 'Karate', category: 'Testing' },
  { value: 'Pact', category: 'Testing' },
  
  // Configuration & Markup
  { value: 'Markdown', category: 'Markup' },
  { value: 'AsciiDoc', category: 'Markup' },
  { value: 'reStructuredText', category: 'Markup' },
  { value: 'Textile', category: 'Markup' },
  { value: 'Org Mode', category: 'Markup' },
  { value: 'LaTeX', category: 'Markup' },
  { value: 'TeX', category: 'Markup' },
  { value: 'Typst', category: 'Markup' },
  { value: 'Groff', category: 'Markup' },
  { value: 'man page', category: 'Markup' },
  { value: 'INI', category: 'Config' },
  { value: 'Properties', category: 'Config' },
  { value: 'HOCON', category: 'Config' },
  { value: 'Dhall', category: 'Config' },
  { value: 'Jsonnet', category: 'Config' },
  { value: 'CUE', category: 'Config' },
  { value: 'Nix', category: 'Config' },
  { value: 'Starlark', category: 'Config' },
  { value: 'KDL', category: 'Config' },
  { value: 'RON', category: 'Config' },
  { value: '.env', category: 'Config' },
  { value: '.editorconfig', category: 'Config' },
  { value: '.gitignore', category: 'Config' },
  { value: '.gitattributes', category: 'Config' },
  { value: '.npmrc', category: 'Config' },
  { value: '.eslintrc', category: 'Config' },
  { value: '.prettierrc', category: 'Config' },
  { value: 'tsconfig.json', category: 'Config' },
  { value: 'package.json', category: 'Config' },
  { value: 'Cargo.toml', category: 'Config' },
  { value: 'go.mod', category: 'Config' },
  { value: 'requirements.txt', category: 'Config' },
  { value: 'Pipfile', category: 'Config' },
  { value: 'pyproject.toml', category: 'Config' },
  { value: 'setup.py', category: 'Config' },
  { value: 'Gemfile', category: 'Config' },
  { value: 'composer.json', category: 'Config' },
  { value: 'pom.xml', category: 'Config' },
  { value: 'build.gradle', category: 'Config' },
  { value: 'build.sbt', category: 'Config' },
  { value: 'mix.exs', category: 'Config' },
  { value: 'cabal', category: 'Config' },
  { value: 'stack.yaml', category: 'Config' },
  { value: 'dune', category: 'Config' },
  { value: 'opam', category: 'Config' },
  
  // Embedded & IoT
  { value: 'Arduino', category: 'Embedded' },
  { value: 'Arduino C++', category: 'Embedded' },
  { value: 'ESP-IDF', category: 'Embedded' },
  { value: 'MicroPython', category: 'Embedded' },
  { value: 'CircuitPython', category: 'Embedded' },
  { value: 'Raspberry Pi Python', category: 'Embedded' },
  { value: 'STM32 HAL', category: 'Embedded' },
  { value: 'PlatformIO', category: 'Embedded' },
  { value: 'Zephyr RTOS', category: 'Embedded' },
  { value: 'FreeRTOS', category: 'Embedded' },
  { value: 'RIOT OS', category: 'Embedded' },
  { value: 'Contiki', category: 'Embedded' },
  { value: 'TinyOS', category: 'Embedded' },
  { value: 'mbed', category: 'Embedded' },
  { value: 'Node-RED', category: 'Embedded' },
  { value: 'MQTT', category: 'Embedded' },
  { value: 'CoAP', category: 'Embedded' },
  { value: 'Modbus', category: 'Embedded' },
  { value: 'CAN Bus', category: 'Embedded' },
  { value: 'I2C', category: 'Embedded' },
  { value: 'SPI', category: 'Embedded' },
  { value: 'UART', category: 'Embedded' },
  { value: 'GPIO', category: 'Embedded' },
  { value: 'PWM', category: 'Embedded' },
  { value: 'ADC/DAC', category: 'Embedded' },
  
  // Historical & Educational
  { value: 'BASIC', category: 'Historical' },
  { value: 'QBasic', category: 'Historical' },
  { value: 'Visual Basic', category: 'Historical' },
  { value: 'VB.NET', category: 'Historical' },
  { value: 'VBA', category: 'Historical' },
  { value: 'FORTRAN', category: 'Historical' },
  { value: 'Fortran 77', category: 'Historical' },
  { value: 'Fortran 90', category: 'Historical' },
  { value: 'Modern Fortran', category: 'Historical' },
  { value: 'COBOL', category: 'Historical' },
  { value: 'PL/I', category: 'Historical' },
  { value: 'ALGOL', category: 'Historical' },
  { value: 'Simula', category: 'Historical' },
  { value: 'Smalltalk', category: 'Historical' },
  { value: 'Prolog', category: 'Historical' },
  { value: 'Datalog', category: 'Historical' },
  { value: 'Logo', category: 'Historical' },
  { value: 'Scratch', category: 'Historical' },
  { value: 'Snap!', category: 'Historical' },
  { value: 'Blockly', category: 'Historical' },
  { value: 'App Inventor', category: 'Historical' },
  { value: 'Alice', category: 'Historical' },
  { value: 'Karel', category: 'Historical' },
  { value: 'Processing', category: 'Historical' },
  { value: 'p5.js', category: 'Historical' },
  { value: 'OpenFrameworks', category: 'Historical' },
  { value: 'Cinder', category: 'Historical' },
  { value: 'Max/MSP', category: 'Historical' },
  { value: 'Pure Data', category: 'Historical' },
  { value: 'SuperCollider', category: 'Historical' },
  { value: 'Sonic Pi', category: 'Historical' },
  { value: 'ChucK', category: 'Historical' },
  { value: 'Csound', category: 'Historical' },
  { value: 'FAUST', category: 'Historical' },
  { value: 'Nyquist', category: 'Historical' },
  
  // Esoteric & Domain-Specific
  { value: 'Brainfuck', category: 'Esoteric' },
  { value: 'Whitespace', category: 'Esoteric' },
  { value: 'Malbolge', category: 'Esoteric' },
  { value: 'INTERCAL', category: 'Esoteric' },
  { value: 'Piet', category: 'Esoteric' },
  { value: 'Befunge', category: 'Esoteric' },
  { value: 'LOLCODE', category: 'Esoteric' },
  { value: 'Chef', category: 'Esoteric' },
  { value: 'Shakespeare', category: 'Esoteric' },
  { value: 'Rockstar', category: 'Esoteric' },
  { value: 'ArnoldC', category: 'Esoteric' },
  { value: 'Emojicode', category: 'Esoteric' },
  { value: 'Cow', category: 'Esoteric' },
  { value: 'Ook!', category: 'Esoteric' },
  { value: 'FALSE', category: 'Esoteric' },
  { value: 'Forth', category: 'Esoteric' },
  { value: 'Factor', category: 'Esoteric' },
  { value: 'PostScript', category: 'Esoteric' },
  { value: 'APL', category: 'Esoteric' },
  { value: 'J', category: 'Esoteric' },
  { value: 'K', category: 'Esoteric' },
  { value: 'Q', category: 'Esoteric' },
  { value: 'BQN', category: 'Esoteric' },
  { value: 'Uiua', category: 'Esoteric' },
  { value: 'Jelly', category: 'Esoteric' },
  { value: '05AB1E', category: 'Esoteric' },
  { value: 'Vyxal', category: 'Esoteric' },
  { value: 'GolfScript', category: 'Esoteric' },
  { value: 'Pyth', category: 'Esoteric' },
  { value: 'Stax', category: 'Esoteric' },
  
  // Blockchain & Smart Contracts
  { value: 'Solidity', category: 'Blockchain' },
  { value: 'Vyper', category: 'Blockchain' },
  { value: 'Rust Solana', category: 'Blockchain' },
  { value: 'Move', category: 'Blockchain' },
  { value: 'Cadence', category: 'Blockchain' },
  { value: 'Clarity', category: 'Blockchain' },
  { value: 'Plutus', category: 'Blockchain' },
  { value: 'Marlowe', category: 'Blockchain' },
  { value: 'Michelson', category: 'Blockchain' },
  { value: 'SmartPy', category: 'Blockchain' },
  { value: 'LIGO', category: 'Blockchain' },
  { value: 'Reach', category: 'Blockchain' },
  { value: 'Scilla', category: 'Blockchain' },
  { value: 'Yul', category: 'Blockchain' },
  { value: 'Huff', category: 'Blockchain' },
  { value: 'ink!', category: 'Blockchain' },
  { value: 'CosmWasm', category: 'Blockchain' },
  { value: 'Anchor', category: 'Blockchain' },
  { value: 'Hardhat', category: 'Blockchain' },
  { value: 'Foundry', category: 'Blockchain' },
  { value: 'Truffle', category: 'Blockchain' },
  { value: 'Brownie', category: 'Blockchain' },
  { value: 'Ape', category: 'Blockchain' },
  { value: 'ethers.js', category: 'Blockchain' },
  { value: 'web3.js', category: 'Blockchain' },
  { value: 'viem', category: 'Blockchain' },
  { value: 'wagmi', category: 'Blockchain' },
  
  // Query Languages
  { value: 'SPARQL', category: 'Query' },
  { value: 'XQuery', category: 'Query' },
  { value: 'XPath', category: 'Query' },
  { value: 'XSLT', category: 'Query' },
  { value: 'JSONPath', category: 'Query' },
  { value: 'JMESPath', category: 'Query' },
  { value: 'jq', category: 'Query' },
  { value: 'yq', category: 'Query' },
  { value: 'OData', category: 'Query' },
  { value: 'LINQ', category: 'Query' },
  { value: 'PartiQL', category: 'Query' },
  { value: 'N1QL', category: 'Query' },
  { value: 'AQL', category: 'Query' },
  { value: 'Gremlin', category: 'Query' },
  { value: 'GSQL', category: 'Query' },
  { value: 'SurrealQL', category: 'Query' },
  { value: 'EdgeQL', category: 'Query' },
  { value: 'Prisma', category: 'Query' },
  { value: 'Drizzle', category: 'Query' },
  { value: 'Knex', category: 'Query' },
  { value: 'Sequelize', category: 'Query' },
  { value: 'TypeORM', category: 'Query' },
  { value: 'Hibernate HQL', category: 'Query' },
  { value: 'JPQL', category: 'Query' },
  { value: 'Criteria API', category: 'Query' },
  { value: 'QueryDSL', category: 'Query' },
  { value: 'JOOQ', category: 'Query' },
  { value: 'SQLAlchemy', category: 'Query' },
  { value: 'Django ORM', category: 'Query' },
  { value: 'Active Record', category: 'Query' },
  { value: 'Ecto', category: 'Query' },
  { value: 'GORM', category: 'Query' },
  
  // Template Languages
  { value: 'Jinja2', category: 'Template' },
  { value: 'Django Templates', category: 'Template' },
  { value: 'Twig', category: 'Template' },
  { value: 'Blade', category: 'Template' },
  { value: 'ERB', category: 'Template' },
  { value: 'Haml', category: 'Template' },
  { value: 'Slim', category: 'Template' },
  { value: 'Pug', category: 'Template' },
  { value: 'Jade', category: 'Template' },
  { value: 'EJS', category: 'Template' },
  { value: 'Handlebars', category: 'Template' },
  { value: 'Mustache', category: 'Template' },
  { value: 'Nunjucks', category: 'Template' },
  { value: 'Liquid', category: 'Template' },
  { value: 'Velocity', category: 'Template' },
  { value: 'FreeMarker', category: 'Template' },
  { value: 'Thymeleaf', category: 'Template' },
  { value: 'Razor', category: 'Template' },
  { value: 'CSHTML', category: 'Template' },
  { value: 'ASPX', category: 'Template' },
  { value: 'JSP', category: 'Template' },
  { value: 'GSP', category: 'Template' },
  { value: 'Marko', category: 'Template' },
  { value: 'Eta', category: 'Template' },
  { value: 'doT', category: 'Template' },
  { value: 'Dust', category: 'Template' },
  { value: 'Swig', category: 'Template' },
  { value: 'Hogan', category: 'Template' },
  { value: 'Rivets', category: 'Template' },
  { value: 'Ractive', category: 'Template' },
  
  // Scientific Computing
  { value: 'Fortran Scientific', category: 'Scientific' },
  { value: 'Chapel', category: 'Scientific' },
  { value: 'X10', category: 'Scientific' },
  { value: 'UPC', category: 'Scientific' },
  { value: 'Co-Array Fortran', category: 'Scientific' },
  { value: 'OpenMP', category: 'Scientific' },
  { value: 'MPI', category: 'Scientific' },
  { value: 'SYCL', category: 'Scientific' },
  { value: 'oneAPI', category: 'Scientific' },
  { value: 'OpenACC', category: 'Scientific' },
  { value: 'HIP', category: 'Scientific' },
  { value: 'ROCm', category: 'Scientific' },
  { value: 'BLAS', category: 'Scientific' },
  { value: 'LAPACK', category: 'Scientific' },
  { value: 'ScaLAPACK', category: 'Scientific' },
  { value: 'PETSc', category: 'Scientific' },
  { value: 'Trilinos', category: 'Scientific' },
  { value: 'SUNDIALS', category: 'Scientific' },
  { value: 'FEniCS', category: 'Scientific' },
  { value: 'deal.II', category: 'Scientific' },
  { value: 'OpenFOAM', category: 'Scientific' },
  { value: 'ANSYS APDL', category: 'Scientific' },
  { value: 'ABAQUS Python', category: 'Scientific' },
  { value: 'COMSOL', category: 'Scientific' },
  { value: 'Gmsh', category: 'Scientific' },
  { value: 'ParaView Python', category: 'Scientific' },
  { value: 'VTK Python', category: 'Scientific' },
  { value: 'VisIt', category: 'Scientific' },
  { value: 'Tecplot', category: 'Scientific' },
  { value: 'gnuplot', category: 'Scientific' },
  { value: 'Asymptote', category: 'Scientific' },
  { value: 'PGF/TikZ', category: 'Scientific' },
  
  // More Languages (Continued)
  { value: 'ABAP', category: 'Enterprise' },
  { value: 'NATURAL', category: 'Enterprise' },
  { value: 'RPG', category: 'Enterprise' },
  { value: 'CL/400', category: 'Enterprise' },
  { value: 'JCL', category: 'Enterprise' },
  { value: 'REXX', category: 'Enterprise' },
  { value: 'CLIST', category: 'Enterprise' },
  { value: 'Easytrieve', category: 'Enterprise' },
  { value: 'FOCUS', category: 'Enterprise' },
  { value: 'CA-Gen', category: 'Enterprise' },
  { value: 'PowerBuilder', category: 'Enterprise' },
  { value: 'Progress 4GL', category: 'Enterprise' },
  { value: 'OpenEdge ABL', category: 'Enterprise' },
  { value: 'Clarion', category: 'Enterprise' },
  { value: 'Clipper', category: 'Enterprise' },
  { value: 'dBase', category: 'Enterprise' },
  { value: 'FoxPro', category: 'Enterprise' },
  { value: 'FileMaker', category: 'Enterprise' },
  { value: 'Access VBA', category: 'Enterprise' },
  { value: 'LotusScript', category: 'Enterprise' },
  { value: '4D', category: 'Enterprise' },
  { value: 'MUMPS', category: 'Enterprise' },
  { value: 'CACHE ObjectScript', category: 'Enterprise' },
  { value: 'LabVIEW', category: 'Enterprise' },
  { value: 'Simulink', category: 'Enterprise' },
  { value: 'SCADE', category: 'Enterprise' },
  { value: 'ControlLogix', category: 'Enterprise' },
  { value: 'Structured Text', category: 'Enterprise' },
  { value: 'Ladder Logic', category: 'Enterprise' },
  { value: 'Function Block Diagram', category: 'Enterprise' },
  { value: 'Sequential Function Chart', category: 'Enterprise' },
  { value: 'Instruction List', category: 'Enterprise' },
  { value: 'GRAFCET', category: 'Enterprise' },
  { value: 'CoDeSys', category: 'Enterprise' },
  { value: 'TwinCAT', category: 'Enterprise' },
  { value: 'Siemens SCL', category: 'Enterprise' },
  { value: 'Siemens STL', category: 'Enterprise' },
  { value: 'GE Fanuc', category: 'Enterprise' },
  { value: 'Allen-Bradley', category: 'Enterprise' },
  { value: 'Mitsubishi PLC', category: 'Enterprise' },
  { value: 'Omron PLC', category: 'Enterprise' },
  { value: 'Schneider PLC', category: 'Enterprise' },
  
  // Additional Modern Languages
  { value: 'Mojo', category: 'Modern' },
  { value: 'Carbon', category: 'Modern' },
  { value: 'Vale', category: 'Modern' },
  { value: 'Gleam', category: 'Modern' },
  { value: 'Roc', category: 'Modern' },
  { value: 'Unison', category: 'Modern' },
  { value: 'Grain', category: 'Modern' },
  { value: 'Ante', category: 'Modern' },
  { value: 'Hare', category: 'Modern' },
  { value: 'Odin', category: 'Modern' },
  { value: 'V', category: 'Modern' },
  { value: 'Vala', category: 'Modern' },
  { value: 'Genie', category: 'Modern' },
  { value: 'Fantom', category: 'Modern' },
  { value: 'Gosu', category: 'Modern' },
  { value: 'Ceylon', category: 'Modern' },
  { value: 'Xtend', category: 'Modern' },
  { value: 'Frege', category: 'Modern' },
  { value: 'Eta', category: 'Modern' },
  { value: 'Koka', category: 'Modern' },
  { value: 'Eff', category: 'Modern' },
  { value: 'Frank', category: 'Modern' },
  { value: 'Links', category: 'Modern' },
  { value: 'Ur/Web', category: 'Modern' },
  { value: 'Opa', category: 'Modern' },
  { value: 'Hop', category: 'Modern' },
  { value: 'Opalang', category: 'Modern' },
  { value: 'Imba', category: 'Modern' },
  { value: 'Mint', category: 'Modern' },
  { value: 'Red', category: 'Modern' },
  { value: 'Rebol', category: 'Modern' },
  { value: 'Self', category: 'Modern' },
  { value: 'Io', category: 'Modern' },
  { value: 'Ioke', category: 'Modern' },
  { value: 'Seph', category: 'Modern' },
  { value: 'Wren', category: 'Modern' },
  { value: 'Squirrel', category: 'Modern' },
  { value: 'ChaiScript', category: 'Modern' },
  { value: 'AngelScript', category: 'Modern' },
  { value: 'GMLscript', category: 'Modern' },
  { value: 'Haxe', category: 'Modern' },
  { value: 'Jai', category: 'Modern' },
  { value: 'Beef', category: 'Modern' },
  { value: 'Lobster', category: 'Modern' },
  { value: 'Pony', category: 'Modern' },
  { value: 'Ballerina', category: 'Modern' },
  { value: 'Bosque', category: 'Modern' },
  { value: 'P', category: 'Modern' },
  { value: 'Dafny', category: 'Modern' },
  { value: 'Whiley', category: 'Modern' },
  { value: 'ATS', category: 'Modern' },
  { value: 'F*', category: 'Modern' },
  { value: 'Low*', category: 'Modern' },
  { value: 'SPARK Ada', category: 'Modern' },
  { value: 'Eiffel', category: 'Modern' },
  { value: 'Sather', category: 'Modern' },
  { value: 'Blue', category: 'Modern' },
  { value: 'Component Pascal', category: 'Modern' },
  { value: 'Zonnon', category: 'Modern' },
  { value: 'Active Oberon', category: 'Modern' },
  { value: 'Seed7', category: 'Modern' },
  { value: 'Euphoria', category: 'Modern' },
  { value: 'Ring', category: 'Modern' },
  { value: 'Harbour', category: 'Modern' },
  { value: 'xHarbour', category: 'Modern' },
  { value: 'Montana', category: 'Modern' },
  { value: 'Oxygene', category: 'Modern' },
  { value: 'RemObjects C#', category: 'Modern' },
  { value: 'Swift for TensorFlow', category: 'Modern' },
  { value: 'S4TF', category: 'Modern' },
  { value: 'JAX', category: 'Modern' },
  { value: 'Triton', category: 'Modern' },
  { value: 'Taichi', category: 'Modern' },
  { value: 'Halide', category: 'Modern' },
  { value: 'TVM', category: 'Modern' },
  { value: 'XLA', category: 'Modern' },
  { value: 'IREE', category: 'Modern' },
  { value: 'ONNX', category: 'Modern' },
  { value: 'TensorRT', category: 'Modern' },
  { value: 'OpenVINO', category: 'Modern' },
  { value: 'CoreML', category: 'Modern' },
  { value: 'NNAPI', category: 'Modern' },
  
  // Regional & Specialized
  { value: 'Wenyan', category: 'Regional' },
  { value: 'Qalb', category: 'Regional' },
  { value: 'Rapira', category: 'Regional' },
  { value: 'Robik', category: 'Regional' },
  { value: 'Lexico', category: 'Regional' },
  { value: 'Fjölnir', category: 'Regional' },
  { value: 'Raptor', category: 'Regional' },
  { value: 'Flowgorithm', category: 'Regional' },
  { value: 'Structorizer', category: 'Regional' },
  { value: 'Larp', category: 'Regional' },
  { value: 'PSeInt', category: 'Regional' },
  { value: 'Portugol', category: 'Regional' },
  { value: 'VisualG', category: 'Regional' },
  { value: 'Algobox', category: 'Regional' },
  { value: 'DRAKON', category: 'Regional' },
];

// Get unique categories for grouping
export const LANGUAGE_CATEGORIES = [
  'Auto',
  'Analysis',
  'Popular',
  'Web',
  'Database',
  'Systems',
  'Functional',
  'Scripting',
  'Mobile',
  'Game Dev',
  'Data Science',
  'DevOps',
  'Testing',
  'Markup',
  'Config',
  'Embedded',
  'Historical',
  'Esoteric',
  'Blockchain',
  'Query',
  'Template',
  'Scientific',
  'Enterprise',
  'Modern',
  'Regional',
];

// Simple array of language values for quick access
export const LANGUAGE_VALUES = PROGRAMMING_LANGUAGES.map(lang => lang.value);

// Get languages by category
export const getLanguagesByCategory = (category: string) => 
  PROGRAMMING_LANGUAGES.filter(lang => lang.category === category);

// Search languages
export const searchLanguages = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return PROGRAMMING_LANGUAGES.filter(lang => 
    lang.value.toLowerCase().includes(lowerQuery) ||
    lang.category.toLowerCase().includes(lowerQuery)
  );
};
